services:
  app:
    image: node:20-alpine
    container_name: nestjs_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: [ "npm", "run", "start:dev" ]
    ports:
      - "3000:3000"